// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://klqzrgguptwlromqioxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtscXpyZ2d1cHR3bHJvbXFpb3h4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4NjMyNTAsImV4cCI6MjA2MjQzOTI1MH0.CthS-dibNnPww0Ry-JhY2BpnCu8uw_qY6NaRLU9V_ug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);